name: CI
on:
  push: { branches: [ main, develop ] }
  pull_request: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with: { version: 9 }

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Approve builds (CI)
        run: pnpm approve-builds --yes

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Unit tests
        run: pnpm test

      - name: Build
        run: pnpm build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: E2E tests
        env: { CI: "1" }
        run: pnpm e2e

      # Optional: GitHub Pages deploy for main
      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v5

      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with: { path: ./dist }

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4
